server:
  port: 8123
  servlet:
    context-path: /api

spring:
  profiles:
    active: local
  #redis
  redis:
    host: localhost
    port: 6379
    database: 1

  #mysql
  datasource:
    username:  root
    password:  123456
    url: jdbc:mysql://localhost:3306/zhao_picture
    driver-class-name: com.mysql.cj.jdbc.Driver

##knife4j
knife4j:
  enable: true
  openapi:
    version: 1.0
    title: 云图库测试文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: 2485259674@qq.com
    concat: zhao-picture
    group:
      Group:
        group-name: zhao-picture
        api-rule: Package
        api-rule-resources:
          - com.zhao.zhaopicturebacked.controller

#mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#定时任务启动
task:
  insertTask:
    isStart: 1 #是否开启定时任务
